### ISSUE TITLE
Add server message to error object

### ISSUE THREAD

**Issue by frappeerpnext** [The-Commit-Company/frappe-js-sdk#31]
When we make request via db or call object, if error occur from backend frappe send friendly message to client via _server_messages key. 
I cannot extract it in .catch((error) { ... }). It seems that you did not include it in error object.

Here is server message when I check in network response.

![image](https://github.com/The-Commit-Company/frappe-js-sdk/assets/109807018/5ee24935-4842-4372-8c4d-0900ece2f1f8)

Could you please help include this message in .catch error object?

Thanks,

**Comment by nikkothari22** [comment]
@frappeerpnext - yes this is something that needs to be added. I'll try adding it in.

**Comment by frappeerpnext** [comment]
Yes, I hope this will be added soon. These error information is very useful and we save a lot time to customize friendly  message to end user.

Thanks,

**Comment by frappeerpnext** [comment]
Hi Guys,
I have update and test it. Working perfect.

Big Thanks
