### ISSUE TITLE
how to add otherData to file when upload file?

### ISSUE THREAD

**Issue by eposrestaurant2023** [The-Commit-Company/frappe-js-sdk#42]
Hi,

When I update file I want to add title and description when submit to api. I check in file/types.ts, I saw property otherData.
I try to send data via this property when I update file.
{
"otherData": {"title": "my file title","description":"my filedescript"}
}

I check in network payload I saw my file information is sent to api, and upload success, but when I check in file manager, title and description is blank.

Can you show me how to send other file infor when we upload file?
Thanks,
Pheakdey

**Comment by nikkothari22** [comment]
Hey @eposrestaurant2023 - the standard Frappe API to upload a file does not support the `title` and `description` fields. 

The `otherData` parameter is added so that if someone uses the file upload function with a custom file upload API, then it would send the otherData alongwith the request.
