### ISSUE TITLE
[BUG] File is not sent in the API call in upload_file function

### ISSUE THREAD

**Issue by Abhishekranjan56** [The-Commit-Company/frappe-js-sdk#49]
**Describe the bug**
I encountered an issue while attempting to upload a file from my local storage using the frappe-js-sdk within a React Native Expo environment. The error message I received was:
{
  "_server_messages": "[{\"message\": \"Invalid request arguments\", \"title\": \"Message\", \"indicator\": \"red\", \"raise_exception\": 1, \"__frappe_exc_id\": \"92b19b1d4c2e616406f1d87a77a136c8ad10eeaf364c6c7af18e6c9e\"}]",
  "exc_type": "ValidationError",
  "exception": "",
  "httpStatus": 417,
  "httpStatusText": undefined,
  "message": "There was an error while uploading the file."
}
This indicates that the request arguments were invalid, leading to a validation error and ultimately preventing the file from being uploaded successfully.

**Expected behavior**
Was expected to upload the image on user dashboard in the field called user_image

The Method I used and the arguments passed are displayed below:
 const myFile = "https://cdn.pixabay.com/photo/2016/11/18/23/38/child-1837375_640.png";
      const fileArgs = {
        isPrivate: true,
        folder: "Home",
        file_url: "",
        doctype: "User",
        docname: "Sub Doc Name",
        fieldname: "image"
      };
      console.log("fileArgs>>>>>", fileArgs);
      file
        .uploadFile(myFile, fileArgs, (completedBytes, totalBytes) =>
          console.log(Math.round((completedBytes / totalBytes) * 100), " completed")
        )
        .then((r) => console.log(r))
        .catch((e) => console.error(e));

**Comment by Abhishekranjan56** [comment]
Ok But even if I tried to upload a file stored in local storage it shows same error.

**Comment by nikkothari22** [comment]
> Ok But even if I tried to upload a file stored in local storage it shows same error. @nikkothari22

Yes, I am investigating it right now. Looks like this is because of the Axios update. Should be fixed by tomorrow.

**Comment by Abhishekranjan56** [comment]
Thank you for tapping on this issue @nikkothari22

**Comment by nikkothari22** [comment]
@Abhishekranjan56 Fixed in v1.4.3: https://github.com/The-Commit-Company/frappe-js-sdk/releases/tag/v1.4.3
