### ISSUE TITLE
CSRF Token

### ISSUE THREAD

**Issue by pipech** [The-Commit-Company/frappe-js-sdk#56]
I'm not sure how CSRF token works on `frappe-js-sdk`.

Base on `axios.ts` file, it set header using value from `windows.csrf_token` but I can't find how `windows.csrf_token` got set in the first place.

If I'm not mistaken frappe didn't even send out `csrf_token` by default, it have been set using python [html rendering function.](https://github.com/frappe/frappe/blob/d11f8e7bcb198362e7e3b67b4a5cda83f444a023/frappe/website/page_renderers/base_template_page.py#L18-L25)

So there has to be modification on both frappe server and js setup right?

https://github.com/The-Commit-Company/frappe-js-sdk/blob/80bd3a0768e8c927d39b5c9217b3931c6187a001/src/utils/axios.ts#L31-L38

**Comment by nikkothari22** [comment]
Yes. You need to pass the CSRF token in the context and then add that to the window object.

All Frappe Vue and React based apps using cookie based authentication are using this format. 

You can check Gameplan or Raven for implementation details.
